compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

nodeLinker: node-modules

npmScopes:
  rocicorp:
    npmRegistryServer: https://registry.npmjs.org/
    npmAlwaysAuth: true
    npmAuthToken: ${YARN_NPM_ACCESS_TOKEN_FOR_ZERO}
